### ISSUE TITLE
Consider being able to explicitly register for a given event name 

### ISSUE THREAD

**Issue by romm** [yiisoft/event-dispatcher#10]
I'm using this library as a standalone package, and I ran into an issue: one of the listener methods does not have an event argument (which is currently needed by the library). This is because this listener needs to run a process at a specific stage of the runtime, but doesn't need any information provided by the event (whereas some other listeners for the same event need it). Adding the event parameter to the said method results in a parameter being unused, which is not acceptable (and reported by static analysis tools).

I completely understand the goal of this library and find it very interesting; however, the limitation I just spoke about is very problematic in that case, and could be the reason why some people may use another package than this one.

I would suggest to either add an optional `$eventName` argument to the `attach` method, or create a new basic provider with this feature which would allow the usage of the aggregate listener provider. I really think the second option would be the best one.

I'm ready to contribute if you tell me what you think of this issue, and what might be the correct solution to your eyes.

**Comment by samdark** [comment]
Yes, we can add another implementation of `ListenerProviderInterface`. It's certainly better than having varying arguments.

**Comment by romm** [comment]
Ok, I'll try to submit a PR so we can discuss the implementation in it, are you ok with that?

**Comment by samdark** [comment]
Yes,

**Comment by xepozz** [comment]
Please share your code in which you have problems

**Comment by romm** [comment]
This is quite simple actually, there is a listener, and it doesn't need an argument — which is not possible with the current state of this library to register it:

```php
$provider = new Yiisoft\EventDispatcher\Provider\Provider();
$dispatcher = new Yiisoft\EventDispatcher\Dispatcher($provider);

$listenerA = function (MyEvent $event) {
    // do something with the event
};
$listenerB = function () {
    // just needs to run at a particular stage and doesn't need an argument
};

$provider->attach($listenerA);
$provider->attach($listenerB); // not possible currently because there is no way to bind it to the event
```
