### ISSUE TITLE
Why cloning ListenerCollection every time when adding a new listener?

### ISSUE THREAD

**Issue by lubobill1990** [yiisoft/event-dispatcher#33]
https://github.com/yiisoft/event-dispatcher/blob/dbc2bcdea947a0868fb998eeb7451f924c8be60f/src/Provider/ListenerCollection.php#L49

I use this package in my project #22 

I find this package is refactored and I'm willing to adapt to my project.

My solution is making a public listener using ListenerCollection to subscribe to events.

And ListenerCollection is singleton so that the dispatcher use the same ListenerCollection.

But the snag is ListenerCollection changes every time when adding a new event handler, so the singleton pattern doesn't work(because of clone).

I'm curious why using clone when adding a new event hander?

At least, doesn't it affect performance?

**Comment by samdark** [comment]
> I'm curious why using clone when adding a new event hander?

To ensure immutability. A good flow when dealing with events is configuring them during application bootstrap and then not adding them dynamically. If you have a use-case for dynamic events, let us know. We'll reconsider design.

> At least, doesn't it affect performance?

Not significantly. `clone` is very fast.

**Comment by lubobill1990** [comment]
@samdark Thanks!

**Comment by olegbaturin** [comment]
> If you have a use-case for dynamic events, let us know.
Всегда пожалуйста. Проблем в текущей реализации на самом деле две. Первая - события со значимым контекстом. Вторая - слушатель/обработчик со своим состоянием.

Первая проблема чуть глубже и довольно часто встречается при проектировании. Ее причина - попытка переноса языка описания из одного контекста в другой с целью упростить/шаблонировать реализацию. В моем случае пример - это обработка котировок. Мне нужно назначить слушателей на событие "пришла котировка заданного тикера".
`new Event(new Quote($ticker, $value))`
В текущей реализации имя события будет одинаковым для всех тикеров - 'quote'. В реальнсти же имя события к примеру для котировки USDRUB будет quote_usdrub, для EURRUB будет quote_eurrub и т.д. Слушателям USDRUB не нужны котровки EURRUB. Как вариант решения проблемы, были предложения сделать классы USDRUBQuote, EURRUBQuote. Это невозможно, потому что в общем случае и конкретно в этом, имена динамические. Могут изменяться, появляться, удаляться. Решение проблемы - получать имя из `NamedEvent::getName()`. Да, это ломает идеальную картину описания имен событий только классами, но так уж они устроены. А пытаться ограничить имена только классами - это утопия.

Вторая проблема гораздо очевиднее на демонах. Тот же пример с котировками. Допустим, есть несколько слушателей у котировки USDRUB. В предложенной реализации мы задаем метод-обработчик новой котировки при старте и он будет одинаково обрабатывать каждую котировку. Это не так. Обработчики бывают не только stateless, но и statefull. Допустим, у нас есть рубли и доллары и есть несколько стратегий их обмена, т.е. несколько типов обработчиков. Каждый обработчик будет обрабатывать одну и ту же котировку USDRUB разным способом. Добавим несколько счетов. В демоне это будет реализовано как несколько объектов-слушателей со своим состоянием, даже если они одного типа. На каждый счёт свой объект. Каждый счёт в любой момент может включаться и выключаться из слушателей. Нам требуется добавлять/удалять слушателей в рантайме и с учетом первой проблемы - каждый на свою котировку, а не на все подряд.
