### ISSUE TITLE
Consider adding EventTrait

### ISSUE THREAD

**Issue by vjik** [yiisoft/event-dispatcher#36]
For using in domain entities.

Logic: entity create events, but send their to dispatcher after save entity.

Example:

```php
final class Post
{
    use EventTrait;

    public function setName(string $name) {
        $this->name = $name;
        $this->recordEvent(new SetNameEvent()); // Save event in entity
    }

    public function setAge(int $age) {
        $this->age = $age;
        $this->recordEvent(new SetAgeEvent()); // Save event in entity
    }
}

final class PostService
{
    public function save(Post $post)
    {
        $this->postRepository->save($post);
        $events = $post->releaseEvents(); // Get all events from entity and clear
        foreach ($events as $event) {
            $this->dispatcher->dispatch($event);
        }
    }
}
```

- [Example of implementation](https://github.com/ElisDN/yii2-demo-aggregates/blob/master/entities/EventTrait.php)

Mentioned in the articles:
- [Decouple your Symfony application using Domain Events](https://romaricdrigon.github.io/2019/08/09/domain-events) (EN)
- [Проектирование сущностей предметной области](https://elisdn.ru/blog/104/domain-entities-modelling) (RU)

**Comment by viktorprogger** [comment]
Conclusion is not to defer events because of their mutational nature. There is no way to process them correctly in this case.
