### ISSUE TITLE
Use fromCallable

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/event-dispatcher#5]
Instead of parsing each type of callable individually, we should at least test the cost of using `Closure::fromCallable`. 
Using this would significantly simplify the code.

**Comment by samdark** [comment]
Benchmark should be put together in order to check it.

**Comment by SamMousa** [comment]
Honestly, I would propose not supporting generic callables altogether.
Having support for invokable objects / closures should be more than enough?

**Comment by samdark** [comment]
Maybe. A benchmark will definitely help to solve this dilemma.

**Comment by SamMousa** [comment]
https://gist.github.com/SamMousa/22dfaf40b89d21748afdd238de2fd8a8

**Comment by KpuTuK** [comment]
What if we add another argument
```php
public function attach(string $eventName, callable $listener): void
    {
        $this->listeners[$eventName][] = $listener;
    }
$provider->attach(Event::class, $listener);
```

**Comment by SamMousa** [comment]
This provider / issue is about using reflection.
We can definitely add another function / create another provider, but it is not related to this issue.

**Comment by samdark** [comment]
@KpuTuK that was how it was done initially but since handler has to type-hint for event anyway, why not to re-use this information?

**Comment by KpuTuK** [comment]
@SamMousa я не совсем понял. плохой английский.

**Comment by SamMousa** [comment]
Sorry @KpuTuK, my Russian is probably much worse than your English ;-)

**Comment by samdark** [comment]
@KpuTuK изначально так и было сделано. Но раз мы указываем интерфейс события в аргументе хендлера, то есть ли смысл делать это два раза?
