### ISSUE TITLE
possible bug with PHP8 and Union type-hint

### ISSUE THREAD

**Issue by ncou** [yiisoft/event-dispatcher#62]
Hi,

Nice piece of code, i think i found a possible problem in php8. I didn't do the test but looking at the code i think in some very very rare case there could have a problem in the code if the php union typehint is used.

at this line of code, the object could be a ReflectionUnionType and not a ReflectionNamedType, so the getName() function will break.
https://github.com/yiisoft/event-dispatcher/blob/master/src/Provider/ListenerCollection.php#L85

Correct me if i am missing something.
Hope this help.

**Comment by vjik** [comment]
Seems, yes. This is bug. Thank you, @ncou .
