### ISSUE TITLE
Improve exception message in `ListenerCollection::add()`

### ISSUE THREAD

**Issue by vjik** [yiisoft/event-dispatcher#64]
Here: https://github.com/yiisoft/event-dispatcher/blob/9fdabc34aef8c64c0141e44985ca81ed1121dbfc/src/Provider/ListenerCollection.php#L99

Need different messages for cases:

- $event is null
- $event not object

**Comment by yiiliveext** [comment]
According to this test https://github.com/yiisoft/event-dispatcher/blob/master/tests/php8/Provider/ListenerCollectionTest.php#L10 
this is a bug
