### ISSUE TITLE
Consider introducing deferred event provider

### ISSUE THREAD

**Issue by SilverFire** [yiisoft/event-dispatcher#7]
Sometimes we use events in transactions, so they should not be dispatched before the transaction is successfully committed. As an example, imagine a user registration flow:

1. Validate data
2. Begin transaction
3. Write user to DBMS
4. Dispatch `UserWasCreated` event
5. Create a profile, catch an exception
6. Rollback transaction

The dependent services may have already sent the welcome email as a result of `UserWasCreated` event handling, but the transaction was reverted later. 

That's why we use an Emitter – a thing that collects events but does not send them to a Dispatcher until `flush()` is called.

The implementation can be pretty dumb:

```php
interface EventDispatcherInterface
{
    public function flush(): void;
}

final class Emitter implements EventDispatcherInterface
{
    private $dispatcher;
    private $events = [];

    public function __construct(EventDispatcherInterface $dispatcher)
    {
        $this->dispatcher = $dispatcher;
    }

    public function dispatch(object $event)
    {
         return $this->events[] = $event;
    }

    public function flush(): void
    {
        foreach ($this->events as $event) {
            $dispatcher->dispatch($event);
        }
    }
}
```

```php
$provider = new Yiisoft\EventDispatcher\Provider\Provider();
$provider->attach(function (UserWasCreated $event) {
    sendGreetingEmail();
});

$dispatcher = new Yiisoft\EventDispatcher\Dispatcher($provider);
$emitter = new Yiisoft\EventDispatcher\Emitter($dispatcher);

$emitter->dispatch(new UserWasCreated($uuid));
// ... flow contiues
$emitter->flush();
```

**Comment by samdark** [comment]
Sounds interesting. Problems I see:

1. If one would use `flush()`, he'd have to rely on `yiisoft/event-dispatcher` explicitly. Currently we're relying on PSR interface only.
2. Most of the time there's no need to flush separately.

It could be solved by introducing `yiisoft/event-dispatcher-delayed` and `EventDispatcherDelayed` interface (emitter is not a good name since there's no hint in it about the fact that events aren't actually being triggered right away). `yiisoft/event-dispatcher` would implement it so application, if needed, may rely on `yiisoft/event-dispatcher-delayed` package.

**Comment by SilverFire** [comment]
I would prefer the word `deferred` instead of `delayed`.

I've got your point. Actually, we can implement a PSR-14-compatible provider that can be used to control events dispatching and it should not be a part of `yiisoft/event-dispatcher` package:

```php
class DeferredDispatchProvider implements ListenerProviderInterface
{
    private $dispatcher;
    private $deferEvents = false;
    private $events = [];

    public function __construct(EventDispatcherInterface $dispatcher) 
    {
        $this->dispatcher = $dispatcher;
    }

    public function getListenersForEvent(object $event): iterable
    {
         if ($this->deferEvents) {
             yield function (object $event) {
                  $this->events[] = $event;
             }
        } else {
             yield function (object $event) {
                 $this->dispatcher->dispatch($event);
             }
        }
    }

    public function catchEvents(): void
    {
        $this->catchEvents = true;
    }

    public function releaseEvents(): array
    {
         $events = $this->events;
         $this->events = [];
         $this->catchEvents = false;

         foreach ($events as $event) {
              $this->dispatcher->dispatch($event);
         }

         return $events;
    }

    public function clearEvents(): void
    {
         $this->events = [];
    }
}
```

```php
$provider = new Yiisoft\EventDispatcher\Provider\Provider();
$dispatcher = new Yiisoft\EventDispatcher\Dispatcher($provider);
$provider->attach(function (UserWasCreated $event) {
    sendGreetingEmail();
});

$deferredDispatcher = new Yiisoft\EventDispatcher\Dispatcher(
    $deferredDispatchProvider = new DeferredDispatchProvider($dispatcher);
);

$deferredDispatchProvider->catchEvents();
$deferredDispatcher->dispatch(new UserWasCreated($uuid));
// ... flow contiues
$deferredDispatchProvider->releaseEvents();
```

**Comment by samdark** [comment]
That's even better. This one can be part of the package, I think.

**Comment by Ziggizag** [comment]
I like the idea. Deferred events are indeed of great value in case of highly interactive application like ticket sales etc.

**Comment by machour** [comment]
I like the initial idea and use case, but I foresee a drawback I see is when using multiple events, if the event depends on the data to be in a certain state:

* data in state A
* event dispatched expecting state A
* data changed to state B
* event dispatched expecting state B

with the new approach, both events would be fired with data at state B.

**Comment by SilverFire** [comment]
@machour it's a general problem of consistency in event-driven systems. You have a few options:

1. You work on an actual aggregate state regardless of how old is the event, that refers to the aggregate (`new UserWasCreated($uuid)`). Then events can be fired on a wrong state.
2. You try to enrich events with the most important aggregate state information (`new UserWasCreated($uuid, $user->email(), $user->phone())`), but you are OK with the fact that when you need some additional information to handle the event, you can retrieve it and, probably, get inconsistent state.
3. You always fulfill events with the full available dataset (`new UserWasCreated(deepcopy($user))`) . Then events are big, you have to make sure that deep copying works as expected (especially with ORM entities and lazyload relations), you can process events with the outdated state, you have to simulate the full aggregate state to produce an event from elsewhere.

Introducing event deferring is neither a solution nor a drawback of an event consistency problem. It's just a tool you can you to make sure that your events are dispatched when the related data is persisted and available to outer systems.

**Comment by lubosdz** [comment]
Sounds interesting - kinda deferred promises a lá ReactPHP :-) 
As an optional core event type would be useful for some scenarios.
Though issues e.g. runtime state-update might be difficult to solve (static bindings).

**Comment by samdark** [comment]
Let's have it. I see no drawbacks adding it to this pacakges instead of creating another one.

**Comment by lubosdz** [comment]
Would be interesting to see unit test(s) for this feature ..

**Comment by vjik** [comment]
Maybe create dispatcher instead provider?

```php
final class DeferredDispatcher implements EventDispatcherInterface
{
    private EventDispatcherInterface $dispatcher;
    private array $events = [];

    public function __construct(EventDispatcherInterface $dispatcher)
    {
        $this->dispatcher = $dispatcher;
    }

    public function dispatch(object $event): object
    {
        $this->events[] = $event;
        return $event;
    }

    public function clear(): void
    {
        $this->events = [];
    }

    public function release(): array
    {
        $events = $this->events;
        $this->clear();

        $dispatchedEvents = [];
        foreach ($events as $event) {
            $dispatchedEvents[] = $this->dispatcher->dispatch($event);
        }

        return $dispatchedEvents;
    }
}
```

... and use so:

```php
$provider = new Yiisoft\EventDispatcher\Provider\Provider();
$dispatcher = new Yiisoft\EventDispatcher\Dispatcher\Dispatcher($provider);

$deferredDispatcher = new Yiisoft\EventDispatcher\Dispatcher\DeferredDispatcher($dispatcher);

$deferredDispatcher->dispatch($event);
$deferredDispatcher->dispatch($event);
//.. others dispatch events

try {
    $this->save();
    $deferredDispatcher->release();
} catch(Exception $e) {
    //rollback logic
}
```

Less code :)

**Comment by samdark** [comment]
@silverfire, @Ziggizag, @machour, @lubosdz, @romkatsu thoughts?

**Comment by yiiliveext** [comment]
```php
//controller action
public function edit(EventDispatcher $dispatcher)
{
    $dispatcher->dispatch(new StartDeferEvents());
    //edit post
    $dispatcher->dispatcher(new PostTitleChanged());      
    
    try {
         $postService->save($post);
         $loggerService->log($post);
         $dispatcher->dispatch(new DispatchDeferredEvents());
    } catch(Exception $e) {
         $dispatcher->dispatch(new RollbackDeferredEvents());
         //rollback logic
    }
}
```

Advantages: 
It is working on any nesting level (inside PostService and LogService and services used by them);
We have clear interface (no PSR interface violation)
Disadvantages: 
It works only with this PSR interface implementation

**Comment by Ziggizag** [comment]
It's better it works only with PSR rather than it does not work with PSR at all :-D

I believe it's fine.

**Comment by samdark** [comment]
@yiiliveext that's a bit unexpected usage of events but, indeed, it solves interface incompatibility issue.

**Comment by samdark** [comment]
Decided not to have it https://github.com/yiisoft/event-dispatcher/pull/39
